### ISSUE TITLE
How to enforce secure cookies

### ISSUE THREAD

**Issue by alexanderadam** [github/secure_headers#449]
# Bugs

In my case the reverse proxy (not under my control) isn't delivering the necessary headers but I need to set the secure flag anyway.

### Expected outcome

Describe what you expected to happen 

```ruby
 config.cookies = {
    secure: true, # mark all cookies as "Secure"
    httponly: true, # mark all cookies as "HttpOnly"
    samesite: {
      strict: true # mark all cookies as SameSite=strict
    }
  }
```

isn't ensuring the `secure` flag.

### Actual outcome

[It doesn't work if some indicating headers aren't available](https://github.com/github/secure_headers/commit/bbabd62c057ab0ebff0cf6ee4d65aa2178ef1a22).

### Config

```ruby
 config.cookies = {
    secure: true, # mark all cookies as "Secure"
    httponly: true, # mark all cookies as "HttpOnly"
    samesite: {
      strict: true # mark all cookies as SameSite=strict
    }
  }
```

Currently I'm using a workaround:

```ruby
SecureHeaders::Middleware.class_eval do
  def override_secure(env, config = {})
    if (Rails.env.development? || Rails.env.test?) && (scheme(env) != "https" && config != SecureHeaders::OPT_OUT)
      config[:secure] = SecureHeaders::OPT_OUT
    end

    config
  end
end
```

but I guess it would be nice to ensure the secure flag via a configuration option.

**Comment by oreoshake** [comment]
Hello, the `secure: true` flag is indeed supposed to set the secure flag. Detecting https with badly behaving proxies is the worst. It's possible that the `scheme(env)` call needs an update. Is this proxy on a shared platform or is it specific to your environment?

Do you have the the headers in `env` available? It would be impossible to diagnose without them.

As long as it's not something wildly uncommon or misconfigured we can make it work but you may need to resort to monkey patching.

The reason it does the detection is so it doesn't send a secure flag in a non-secure context. I can't recall off the top of my head happens when you do that:

1. The browser strips the secure flag
2. The browser sets the cookie for the incorrect context (not available on subsequent non-https contexts)
3. The browser doesn't set the cookie at all

If nearly every browser strips the secure flag, I'd say this is unnecessary. But if the other options exist in even one major browser I'd say the code that overrides the secure flag configuration is necessary.

**Comment by alexanderadam** [comment]
Wow, Neil! You're insanely fast with answering! :laughing: 

>  Is this proxy on a shared platform or is it specific to your environment?

It's very specific to this particular environment.

> Do you have the the headers in `env` available?

You mean some HTTPS headers?
Unfortunately I can't see any (I inspected `env` and searched for `https` and `secure`).

> As long as it's not something wildly uncommon or misconfigured we can make it work but you may need to resort to monkey patching.

Well, my solution by overriding `SecureHeaders::Middleware#override_secure` works already.

> The reason it does the detection is so it doesn't send a secure flag in a non-secure context.

I absolutely understand that. It's just that I obviously need to enforce it anyway. :wink:

**Comment by oreoshake** [comment]
> You mean some HTTPS headers?
> Unfortunately I can't see any (I inspected `env` and searched for `https` and `secure`).

These values would be the ones we work with:

https://github.com/github/secure_headers/blob/ffec182a2da8fc0d245d99e7f9cbd1c9da1a5e95/lib/secure_headers/middleware.rb#L44-L49

I'm not sure if your `env` contains anything that would be useful that's not in that list. I could also see a configuration option that says "set the secure flag no matter what."

**Comment by alexanderadam** [comment]
I don't think that I have to maintain anything in this project anymore so I will close this for now. :wink:
