### ISSUE TITLE
RubyGems doesn't have latest version of this gem

### ISSUE THREAD

**Issue by zmariscal** [github/secure_headers#513]
# Bugs
Currently there hasn't been a successful update on this gem since [6.5.0 according to RubyGems](https://rubygems.org/gems/secure_headers). However there's been two releases since then and those have failed.  Here's the [latest attempt](https://github.com/github/secure_headers/actions/runs/5870033269/job/15916250507#step:3:11).

### Expected outcome
The publish job successfully updates the gem

### Actual outcome
Gem hasn't been successfully updated since `6.5.0` on RubyGems
```[tasklist]
### Tasks
```

**Comment by adeherdt-r7** [comment]
would be great to get feedback about this as well....

**Comment by rzhade3** [comment]
Hey @zmariscal, thanks for filing this issue! I've gone ahead and manually published the gem to Rubygems.org. 

It looks like the `publish` action is designed to publish this Gem to GitHub Releases, not necessarily Rubygems or GitHub Package Registry. I'll see if we can update the Action to automatically publish instead of requiring a manual deployment, or at the very least will update our README to remind us to publish when a new release is made. However, since we now have parity between this gem and Rubygems.org, I'm going to consider this issue complete 👍
